# Generated by Django 3.2.11 on 2022-01-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
